---
# This playbook will install Apache Web Server with php and mysql support
- name: linux_deploy_httpd
  hosts: all
  tasks:
  - name: Install HTTPD
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - httpd
    when: ansible_os_family == "RedHat"

  - name: Setting default HTTP Server page
    shell: echo "<h1>welcome to Miztiik Ansible Playbook Demo</h1>" >> /var/www/html/index.html

  - name: Start Apache Webserver
    service:
      name: httpd
      state: restarted

  - name: enable apache on startup and start service for redhat or centos
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat"
